/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        secondary: "#4c616c",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#e0e0ff",
        primary: "#000666",
        "on-primary-fixed-variant": "#343d96",
        "secondary-fixed": "#cfe6f2",
        "primary-fixed-dim": "#bdc2ff",
        "tertiary-fixed": "#ffdad6",
        "on-surface": "#191c1d",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9fa",
        "on-tertiary-fixed": "#410003",
        "inverse-surface": "#2e3132",
        "inverse-primary": "#bdc2ff",
        "on-tertiary-fixed-variant": "#930010",
        "primary-container": "#1a237e",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        background: "#f8f9fa",
        "surface-container-highest": "#e1e3e4",
        error: "#ba1a1a",
        "surface-container": "#edeeef",
        "surface-container-low": "#f3f4f5",
        "surface-dim": "#d9dadb",
        "secondary-container": "#cfe6f2",
        "on-secondary-container": "#526772",
        surface: "#f8f9fa",
        "on-tertiary": "#ffffff",
        outline: "#767683",
        "outline-variant": "#c6c5d4",
        "on-surface-variant": "#454652",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#b4cad6",
        "on-primary-fixed": "#000767",
        "tertiary-container": "#670008",
        "inverse-on-surface": "#f0f1f2",
        "on-primary-container": "#8690ee",
        "surface-variant": "#e1e3e4",
        "on-tertiary-container": "#ff635b",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#354a53",
        "on-secondary-fixed": "#071e27",
        "tertiary-fixed-dim": "#ffb3ac",
        tertiary: "#400003",
        "surface-container-high": "#e7e8e9",
        "surface-tint": "#4c56af",
        "on-background": "#191c1d",
      },
      fontFamily: {
        headline: ["Public Sans", "sans-serif"],
        body: ["Public Sans", "sans-serif"],
        label: ["Public Sans", "sans-serif"],
        "public-sans": ["Public Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
}
